# Generated by Django 3.0.7 on 2022-01-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesaver', '0003_auto_20220106_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='images',
            field=models.ManyToManyField(blank=True, to='routesaver.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
